### PR TITLE
Grade for Class 3 Assignment

### PR DESCRIPTION
**Pull request by ryansobol**
#### Exercise 1
- No crashes, works as expected. 4 points
- Extra new lines helps with readability :eyes: 
- Favor shorthand reassignment operators whenever possible :rabbit2: 
- `puts` doesn't need an empty string argument to output a blank line :zap: 
#### Exercise 2
- No crashes, but unfortunately it doesn't work as expected. 3 points
- It should output `"NO, NOT SINCE 1938!"` whenever the user types in all uppercase letters
- Also, it should be a random year **each time**
- It should output `"HUH?!  SPEAK UP, SONNY!"` for all other cases
- Favor `loop do` over `while true` for infinite loops
#### Exercise 3
- No crashes, but unfortunately it doesn't work as expected. 3 points
- It demonstrates the same problems as exercise 2, so there's no need to penalize you twice. +1 point
- Good job with the break condition for `while`
#### Exercise 4
- Nothing submitted. 0 points
- I recommend submitting a working program ASAP for at least partial credit
#### Total

`4 + 3 + 3 + 1 + 0 = 11`

### CODE REVIEW

**Comment by mlee1974** [comment]
Hi Ryan - weird my github shows leap year there

here’s a screen shot

**Comment by mlee1974** [comment]
Morning - I ran git push again

Let me know if you’re not seeing it, The last commit shows 2 days ago.  Sorry I’m not sure why you didn’t see anything

**Comment by ryansobol** [comment]
I found out the problem. Can you unmerge this pull request?

**Comment by mlee1974** [comment]
Sure is there command git unmerge command? (didn’t see one in the cheat sheet)

Thanks

**Comment by ryansobol** [comment]
Let's chat in realtime. Can you get on Gitter.IM?

**Pull request merged**
